### ISSUE TITLE
liblcm: make the feature/nuget branch the main development branch

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1014]
- [x] merge `master` into `feature/nuget` again
- [x] announce that the merge of the `feature/nuget` branch will be made the main development branch
- [ ] create a git tag on master (`pre-nuget` ?) before doing the merge
- [x] merge `feature/nuget` into `master`. Doing this requires adjusting the path to the `CHANGELOG.md` file in the .csproj as well as adjusting `GitVersion.yml` (removing settings for `feature/nuget` branch).
- [x] create a release of the nuget packages, and use these released nuget packages in the other projects.

**Comment by tombogle** [comment]
The PR represents my attempt at merging master into feature/nuget: https://github.com/sillsdev/liblcm/pull/164
There does not appear to be any kind of build for this on TeamCity, nor any automated PR build anywhere that reports status to GitHub, so I can't tell whether the current test failures are new or existing or whether they may be caused by something on my machine.
