### ISSUE TITLE
 New LanguageChooser() incorrectly add -Latn to the code of many languages

### ISSUE THREAD

**Issue by hatton** [sillsdev/libpalaso#314]
Examples: Papua New Guinea: etr, gaj, oro, snc, tbg. Nigeria: kcg, mzk, jen

![image](https://cloud.githubusercontent.com/assets/8448/11009108/219d129a-8492-11e5-91bb-310d183aa699.png)

Comparing those languages with the problem with those without it, the pattern I see is that, on Ethnologue.com,  those languages where the script information is displayed have grown this "-Latn" part of their tag:

![image](https://cloud.githubusercontent.com/assets/8448/11009304/2f00d98e-8493-11e5-93a9-53949e32a75e.png)

**Comment by ddaspit** [comment]
I spoke to Martin H. In this case, the "Latn" script has been added on purpose. Apparently, the language tags for writing systems should have a script specified unless the script is implicit. The IANA subtag registry contains a "Suppress-Script" field, which specifies what the implicit script is for a language. For example, "en" does not require a script subtag, because the IANA subtag registry specifies "Latn" as the implicit script. The "etr" language subtag does not have a "Suppress-Script" field, so a script should be specified. Most users do not care about what language tag is used. Is there some issue with some languages having a script subtag specified? Is it a searching issue? I guess that it is possible that If you search for a specific language subtag code and that language has a script subtag specified, you could end up with a different language listed first in the results. Is that the issue?

**Comment by ddaspit** [comment]
After further investigation, it seems that the SLDR does not apply the script rules that I mentioned in the previous comment consistently. There are some languages that do not have a "Suppress-Script" field and do not have a script subtag specified. I think I need to discuss this with Martin more.

**Comment by ddaspit** [comment]
I spoke to Martin again. He told me that the languages that do not have a "Suppress-Script" field and do not have a script subtag specified are incorrect. He hopes to fix it so that all languages either have a "Suppress-Script" field specified or have a script specified explicitly in the tag.

**Comment by ddaspit** [comment]
I took a look at the code and found that searching shouldn't be an issue. If a user searches for a language tag and that language tag is an exact match for the language subtag part of a tag that has a script specified, it will show up first in the list.

**Comment by hatton** [comment]
Thanks for checking on that, @ddaspit. Unless the suppress-script thing is going to get done soon, perhaps we can just remove the script tag for entries for which there is only one script in the inventory.  Is that something that can be done quickly on the fly, or pre-processed?

**Comment by ddaspit** [comment]
I'm still not sure why we need to remove the script subtag. If we remove the script subtag, it will no longer match the tag for the LDML file in the SLDR. Does it make a difference to the user if it is there?

**Comment by hatton** [comment]
> I'm still not sure why we need to remove the script subtag.

Maybe the spec will help you:  [BCP 47 spec, section 3.1.9](https://tools.ietf.org/html/bcp47#section-3.1.9):

> This field indicates a script used to write the overwhelming majority of documents for the given language.  The subtag for such a script therefore adds no distinguishing information to a language tag and thus SHOULD NOT be used for most documents in that language.

It should not be used in languages with a single script. It is apparently a flaw in the data you are sucking this from, as Martin explained (they should have a suppress-subtag). So you can say "well it's not my fault the data is bad".

> Does it make a difference to the user if it is there?

Yes.This is an unacceptable addition of wrong data, adding complexity and confusion, to our shipping UI.  Please remove it. Perhaps the SLDR will have to be fixed to work properly with BCP 47... that's not my area. This UI is.

**Comment by gmartin7** [comment]
@ddaspit Please note this is causing problems for me with "my" language. If I search for the Ethnologue code "sok", I get among the languages "Sok" with code 'skk' and "Sokoro" with code 'sok-Latn', but no option for ethnologue code 'sok'. I already have Bloom books created that use lang code 'sok', but once I switch the language and try to go back there is no way to do it. This results in the appearance of lost data and much frustration for the user. All materials in the Sokoro language are in Latin script (so far, although a modified arabic script would also be a possibility).

**Comment by hatton** [comment]
>  Add new redundant codes if you HAVE to

No, that too is not ok, sorry.

**Comment by ddaspit** [comment]
@gmartin7 I certainly hear what you are saying about taking away codes that are already being used in existing data.

@hatton That section of BCP 47 is referring to languages that have a "Suppress-Script" field specified. As the spec states, if a language has a "Suppress-Script" field specified, you should not specify that script subtag in the language tag. The languages in the LanguageLookupDialog where you are seeing a script subtag are for languages that do not have a "Suppress-Script" field specified. NRSI and ScriptSource wanted to the script to be explicit for languages where there is no "Suppress-Script" field, thus the addition of the script subtag in these cases.

I spoke to Martin more about this issue, trying to come up with a way that meets both your requirements and NRSI's requirements. I think we came up with a solution that will work. Instead of relying on the "Suppress-Script" field in the IANA Subtag Registry to determine the implicit scripts for a language, the Palaso library will use a data file that NRSI generates for listing all of the language tags contained in the SLDR and their relationships to each other. From this file, we can find that the default script for a language. For example, we can find that the default script for "oro" is "Latn". Using this information, we can map the user requested "oro" writing system back to "oro-Latn" when interacting with the SLDR, so that the correct LDML file is downloaded. We can then strip off the "Latn" subtag on the local machine because we know that it is the default script. It will certainly add more complexity to the current implementation, but I think we can make it work. I am working on it now.

**Comment by hatton** [comment]
> That section of BCP 47 is referring to languages that have a "Suppress-Script" field specified.

Right. And as you said, there is no question but that these language should have it specified. So the language chooser was changed to use a new source of SIL data which is itself incorrect. I get that. And it sounds like we all agree that we can't allow that to mess up our users. It's not *their data* that has the problem, it's ours.

Thanks for working on this... we're near to getting this out in our next beta. I'll get your other pr reviewed now.

**Comment by ddaspit** [comment]
The fix for this has been merged into the master branch.
